---

- name: Add Docker repository key
  apt_key: url="https://get.docker.io/gpg" id="{{ docker_repo_key }}" state=present

- name: Add Docker repository
  apt_repository: repo='{{ docker_repo }}' state=present update_cache=yes

- name: Install Docker
  apt: name={{ item }} state=latest
  with_items: docker_packages

- name: Start Docker
  service: name=docker state=started

- name: Check if /etc/default/ufw exists
  stat: path=/etc/default/ufw
  register: ufw_default_exists

- name: Change ufw default forward policy from drop to accept
  lineinfile: dest=/etc/default/ufw regexp="^DEFAULT_FORWARD_POLICY=" line="DEFAULT_FORWARD_POLICY=\"ACCEPT\""
  when: ufw_default_exists.stat.exists
