---
# Installs java 7

- name: Install java (add ppa)
  apt_repository: repo='ppa:webupd8team/java' update_cache=yes

- name: Automatically select the Oracle License
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
  changed_when: False

- name: Install java 7
  apt: name=oracle-java7-installer
