---

- name: Install powerline
  remote_user: '{{ username }}'
  sudo: false
  pip: name='{{ powerline_package }}' extra_args='--user' state=present

- name: Home .fonts folder
  remote_user: '{{ username }}'
  sudo: false
  file: path='{{ item }}' state=directory owner={{ username }}
  with_items:
    - '{{ user_home }}/.config/fontconfig/conf.d'
    - '{{ user_home }}/.fonts'

- name: Get font
  remote_user: '{{ username }}'
  sudo: false
  get_url: url='{{ powerline_font_url }}' dest='{{ user_home }}/.fonts/PowerlineSymbols.otf' owner={{ username }}
  notify:
    - update font cache

- name: Get font config
  remote_user: '{{ username }}'
  sudo: false
  get_url: url='{{ powerline_font_conf_url }}'
           dest='{{ user_home }}/.config/fontconfig/conf.d/10-powerline-symbols.conf'
           owner={{ username }}

- name: Copy configs
  remote_user: '{{ username }}'
  sudo: false
  command: cp -R {{ powerline_home }}/config_files/* {{ user_home }}/.config/powerline
           creates='{{ user_home }}/.config/powerline'
