---

- name: Add sublime repository
  apt_repository: repo={{ sublime_repo }} state=present update_cache=yes

- name: Install sublime
  apt: name={{ item }} state=present
  with_items: sublime_packages
