---
- name: Install ntp
  apt: pkg=ntp state=present force=yes

- name: NTP config
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=true
