---

- name: Download pyenv-installer
  get_url: url={{ pyenv_installer }} dest=/var/cache/pyenv-installer mode=555

- name: Install pyenv
  remote_user: '{{ username }}'
  sudo: false
  shell: /var/cache/pyenv-installer
         executable=/bin/bash
         creates={{ user_home }}/.pyenv
